apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    tier: frontend
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
