apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
  ports:
  - name: “80”
    port: 80
    targetPort: 80