#Types of Services
#1 ClusterIP
#2 NodePort
#3 LoadBalancer
#4 ExternalPort

# Listen on port 8080 locally and forward to port 80 in Pod
#*Kubectl port forward pod/[pod name] 8080:80

# Listen on port 8080 locally and forward to Deployment's Pod
#*Kubectl port forward deployment/[deployment name] 8080

# Listen on port 8080 locally and forward to Service's Pod
#*Kubectl port forward service/[service name] 8080

apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: my-nginx
  ports:
  - port: 8080
    targetPort: 80
